import { Corridor } from "./types";

export const CORRIDORS: Array<Corridor> = [
  {
    id: 1,
    corridorName: "25th St E",
    routeName: "25th St E",
    terminus: "",
    type: "Streetcar",
    description: "",
    mainColor: "#00ff00",
    yearStart: 1890,
    yearEnd: 1954,
    photos: [],
    source: "Met Council Data",
  },
  {
    id: 2,
    corridorName: "28th Ave_34th Ave",
    routeName: "28th Ave to 34th Ave",
    terminus: "",
    type: "Streetcar",
    description: "North Emerson",
    mainColor: "#00ff00",
    yearStart: 1889,
    yearEnd: 1954,
    photos: [],
    source: "Met Council Data",
  },

  {
    id: 3,
    corridorName: "2nd St NE",
    routeName: "2nd St NE",
    terminus: "",
    type: "Streetcar",
    description: "",
    mainColor: "#00ff00",
    yearStart: 1890,
    yearEnd: 1915,
    photos: [],
    source: "Met Council Data",
  },
  {
    id: 4,
    corridorName: "4th Ave",
    routeName: "4th Ave",
    terminus: "",
    type: "Streetcar",
    description: "",
    mainColor: "#00ff00",
    yearStart: null,
    yearEnd: null,
    photos: [],
    source: "Met Council Data",
  },
  {
    id: 5,
    corridorName: "6th Ave N",
    routeName: "6th Ave N",
    terminus: "",
    type: "Streetcar",
    description: "",
    mainColor: "#00ff00",
    yearStart: 1890,
    yearEnd: 1893,
    photos: [],
    source: "Met Council Data",
  },
  {
    id: 6,
    corridorName: "Bloomington Ave",
    routeName: "Bloomington Ave",
    terminus: "",
    type: "Streetcar",
    description: "",
    mainColor: "#00ff00",
    yearStart: 1892,
    yearEnd: 1933,
    photos: [],
    source: "Met Council Data",
  },
  {
    id: 7,
    corridorName: "Ferry",
    routeName: "Express Boat",
    terminus: "",
    type: "Ferry",
    description: "",
    mainColor: "#00ff00",
    yearStart: null,
    yearEnd: 1954,
    photos: [],
    source: "Met Council Data",
  },
  {
    id: 8,
    corridorName: "Broadway",
    routeName: "Broadway",
    terminus: "",
    type: "Streetcar",
    description: "",
    mainColor: "#00ff00",
    yearStart: 1891,
    yearEnd: 1954,
    photos: [],
    source: "Met Council Data",
  },

  {
    id: 9,
    corridorName: "Bryant Ave S",
    routeName: "Bryant Ave S",
    terminus: "",
    type: "Streetcar",
    description: "Terminus at 56th St",
    mainColor: "#00ff00",
    yearStart: 1890,
    yearEnd: 1954,
    photos: [],
    source: "Met Council Data",
  },

  {
    id: 10,
    corridorName: "Bryn Maur",
    routeName: "Bryn Maur",
    terminus: "",
    type: "Streetcar",
    description: "",
    mainColor: "#00ff00",
    yearStart: 1890,
    yearEnd: 1933,
    photos: [],
    source: "Met Council Data",
  },

  {
    id: 11,
    corridorName: "Cable Car",
    routeName: "Cable Car",
    terminus: "",
    type: "Cable Car",
    description: "",
    mainColor: "#00ff00",
    yearStart: 1886,
    yearEnd: 1891,
    photos: [],
    source: "Met Council Data",
  },

  {
    id: 12,
    corridorName: "Cherokee",
    routeName: "Cherokee",
    terminus: "",
    type: "Streetcar",
    description: "",
    mainColor: "#00ff00",
    yearStart: 1890,
    yearEnd: 1954,
    photos: [],
    source: "Met Council Data",
  },

  {
    id: 13,
    corridorName: "Chicago Ave",
    routeName: "Chicago Ave",
    terminus: "",
    type: "Streetcar",
    description: "",
    mainColor: "#00ff00",
    yearStart: 1890,
    yearEnd: 1954,
    photos: [],
    source: "Met Council Data",
  },

  {
    id: 14,
    corridorName: "Columbia Heights",
    routeName: "Columbia Heights",
    terminus: "",
    type: "Streetcar",
    description: "",
    mainColor: "#00ff00",
    yearStart: 1891,
    yearEnd: 1954,
    photos: [],
    source: "Met Council Data",
  },

  {
    id: 15,
    corridorName: "Como_Harriet_Oak_Xer",
    routeName: "Como Harriet Oak",
    terminus: "",
    type: "Streetcar",
    description: "",
    mainColor: "#00ff00",
    yearStart: 1880,
    yearEnd: 1954,
    photos: [],
    source: "Met Council Data",
  },

  {
    id: 16,
    corridorName: "Dale St",
    routeName: "Dale St",
    terminus: "",
    type: "Streetcar",
    description: "",
    mainColor: "#00ff00",
    yearStart: 1890,
    yearEnd: 1954,
    photos: [],
    source: "Met Council Data",
  },

  {
    id: 17,
    corridorName: "Fort Snelling",
    routeName: "Fort Snelling",
    terminus: "",
    type: "Streetcar",
    description: "",
    mainColor: "#00ff00",
    yearStart: 1890,
    yearEnd: 1954,
    photos: [],
    source: "Met Council Data",
  },

  {
    id: 18,
    corridorName: "Franklin",
    routeName: "Franklin",
    terminus: "",
    type: "Streetcar",
    description: "",
    mainColor: "#00ff00",
    yearStart: 1889,
    yearEnd: 1954,
    photos: [],
    source: "Met Council Data",
  },

  {
    id: 19,
    corridorName: "Glenwood Ave",
    routeName: "Glenwood Ave",
    terminus: "",
    type: "Streetcar",
    description: "",
    mainColor: "#00ff00",
    yearStart: 1891,
    yearEnd: 1954,
    photos: [],
    source: "Met Council Data",
  },

  {
    id: 20,
    corridorName: "Grand Ave S",
    routeName: "Grand Ave S",
    terminus: "",
    type: "Streetcar",
    description: "",
    mainColor: "#00ff00",
    yearStart: 1890,
    yearEnd: 1954,
    photos: [],
    source: "Met Council Data",
  },

  {
    id: 21,
    corridorName: "Hamline",
    routeName: "Hamline",
    terminus: "",
    type: "Streetcar",
    description: "",
    mainColor: "#00ff00",
    yearStart: 1891,
    yearEnd: 1906,
    photos: [],
    source: "Met Council Data",
  },

  {
    id: 22,
    corridorName: "Hazel Park",
    routeName: "Hazel Park",
    terminus: "",
    type: "Streetcar",
    description: "",
    mainColor: "#00ff00",
    yearStart: 1889,
    yearEnd: 1954,
    photos: [],
    source: "Met Council Data",
  },

  {
    id: 23,
    corridorName: "Hope",
    routeName: "Hope",
    terminus: "",
    type: "Streetcar",
    description: "",
    mainColor: "#00ff00",
    yearStart: 1889,
    yearEnd: 1954,
    photos: [],
    source: "Met Council Data",
  },

  {
    id: 24,
    corridorName: "Jackson St",
    routeName: "Jackson St",
    terminus: "",
    type: "Streetcar",
    description: "",
    mainColor: "#00ff00",
    yearStart: 1892,
    yearEnd: 1938,
    photos: [],
    source: "Met Council Data",
  },

  {
    id: 25,
    corridorName: "Johnson St NE",
    routeName: "Johnson St NE",
    terminus: "",
    type: "Streetcar",
    description: "",
    mainColor: "#00ff00",
    yearStart: 1890,
    yearEnd: 1954,
    photos: [],
    source: "Met Council Data",
  },

  {
    id: 26,
    corridorName: "Kenwood_StLouisPark",
    routeName: "Kenwood to St. Louis Park",
    terminus: "",
    type: "Streetcar",
    description: "",
    mainColor: "#00ff00",
    yearStart: 1891,
    yearEnd: 1954,
    photos: [],
    source: "Met Council Data",
  },

  {
    id: 27,
    corridorName: "Maria",
    routeName: "Maria",
    terminus: "",
    type: "Streetcar",
    description: "",
    mainColor: "#00ff00",
    yearStart: 1889,
    yearEnd: 1954,
    photos: [],
    source: "Met Council Data",
  },

  {
    id: 28,
    corridorName: "Minnehaha",
    routeName: "Minnehaha",
    terminus: "",
    type: "Streetcar",
    description: "",
    mainColor: "#00ff00",
    yearStart: 1890,
    yearEnd: 1954,
    photos: [],
    source: "Met Council Data",
  },

  {
    id: 29,
    corridorName: "Mississippi St",
    routeName: "Mississippi St",
    terminus: "",
    type: "Streetcar",
    description: "",
    mainColor: "#00ff00",
    yearStart: 1890,
    yearEnd: 1954,
    photos: [],
    source: "Met Council Data",
  },

  {
    id: 30,
    corridorName: "Monroe St NE",
    routeName: "Monroe St NE",
    terminus: "",
    type: "Streetcar",
    description: "",
    mainColor: "#00ff00",
    yearStart: 1891,
    yearEnd: 1954,
    photos: [],
    source: "Met Council Data",
  },

  {
    id: 31,
    corridorName: "Nicollet",
    routeName: "Nicollet",
    terminus: "",
    type: "Streetcar",
    description: "",
    mainColor: "#00ff00",
    yearStart: 1890,
    yearEnd: 1954,
    photos: [],
    source: "Met Council Data",
  },

  {
    id: 32,
    corridorName: "NW Terminal",
    routeName: "NW Terminal",
    terminus: "",
    type: "Streetcar",
    description: "",
    mainColor: "#00ff00",
    yearStart: 1890,
    yearEnd: 1954,
    photos: [],
    source: "Met Council Data",
  },

  {
    id: 33,
    corridorName: "Payne Ave",
    routeName: "Payne Ave",
    terminus: "",
    type: "Streetcar",
    description: "",
    mainColor: "#00ff00",
    yearStart: 1889,
    yearEnd: 1954,
    photos: [],
    source: "Met Council Data",
  },

  {
    id: 34,
    corridorName: "Penn_Fremont",
    routeName: "Penn Fremont",
    terminus: "",
    type: "Streetcar",
    description: "",
    mainColor: "#00ff00",
    yearStart: 1891,
    yearEnd: 1954,
    photos: [],
    source: "Met Council Data",
  },

  {
    id: 35,
    corridorName: "Phalen",
    routeName: "Phalen",
    terminus: "",
    type: "Streetcar",
    description: "",
    mainColor: "#00ff00",
    yearStart: 1889,
    yearEnd: 1954,
    photos: [],
    source: "Met Council Data",
  },

  {
    id: 36,
    corridorName: "Plymouth Ave",
    routeName: "Plymouth Ave",
    terminus: "",
    type: "Streetcar",
    description: "",
    mainColor: "#00ff00",
    yearStart: 1890,
    yearEnd: 1954,
    photos: [],
    source: "Met Council Data",
  },

  {
    id: 37,
    corridorName: "Randolph",
    routeName: "Randolph",
    terminus: "",
    type: "Streetcar",
    description: "",
    mainColor: "#00ff00",
    yearStart: 1890,
    yearEnd: 1954,
    photos: [],
    source: "Met Council Data",
  },

  {
    id: 38,
    corridorName: "Rice St",
    routeName: "Rice St",
    terminus: "",
    type: "Streetcar",
    description: "",
    mainColor: "#00ff00",
    yearStart: 1891,
    yearEnd: 1954,
    photos: [],
    source: "Met Council Data",
  },

  {
    id: 39,
    corridorName: "Robbinsdale",
    routeName: "Robbinsdale",
    terminus: "",
    type: "Streetcar",
    description: "",
    mainColor: "#00ff00",
    yearStart: 1890,
    yearEnd: 1954,
    photos: [],
    source: "Met Council Data",
  },

  {
    id: 40,
    corridorName: "Robert St",
    routeName: "Robert St",
    terminus: "",
    type: "Streetcar",
    description: "",
    mainColor: "#00ff00",
    yearStart: 1891,
    yearEnd: 1954,
    photos: [],
    source: "Met Council Data",
  },

  {
    id: 41,
    corridorName: "Rondo",
    routeName: "Rondo",
    terminus: "",
    type: "Streetcar",
    description: "",
    mainColor: "#00ff00",
    yearStart: 1891,
    yearEnd: 1954,
    photos: [],
    source: "Met Council Data",
  },

  {
    id: 42,
    corridorName: "Saint Clair",
    routeName: "Saint Clair",
    terminus: "",
    type: "Streetcar",
    description: "",
    mainColor: "#00ff00",
    yearStart: 1890,
    yearEnd: 1954,
    photos: [],
    source: "Met Council Data",
  },

  {
    id: 43,
    corridorName: "Selby Lake",
    routeName: "Selby Lake",
    terminus: "",
    type: "Streetcar",
    description: "",
    mainColor: "#00ff00",
    yearStart: 1888,
    yearEnd: 1954,
    photos: [],
    source: "Met Council Data",
  },

  {
    id: 44,
    corridorName: "Snelling Ave",
    routeName: "Snelling Ave",
    terminus: "",
    type: "Streetcar",
    description: "",
    mainColor: "#00ff00",
    yearStart: 1891,
    yearEnd: 1954,
    photos: [],
    source: "Met Council Data",
  },

  {
    id: 45,
    corridorName: "South St Paul",
    routeName: "South St Paul",
    terminus: "",
    type: "Streetcar",
    description: "",
    mainColor: "#00ff00",
    yearStart: 1891,
    yearEnd: 1954,
    photos: [],
    source: "Met Council Data",
  },

  {
    id: 46,
    corridorName: "StPaul_Minneapolis",
    routeName: "StPaul_Minneapolis",
    terminus: "",
    type: "Streetcar",
    description: "",
    mainColor: "#00ff00",
    yearStart: 1890,
    yearEnd: 1954,
    photos: [],
    source: "Met Council Data",
  },

  {
    id: 47,
    corridorName: "Stryker Ave",
    routeName: "Stryker Ave",
    terminus: "",
    type: "Streetcar",
    description: "",
    mainColor: "#00ff00",
    yearStart: 1890,
    yearEnd: 1954,
    photos: [],
    source: "Met Council Data",
  },

  {
    id: 48,
    corridorName: "Stillwater Streetcar",
    routeName: "Stillwater Streetcar",
    terminus: "",
    type: "Streetcar",
    description: "",
    mainColor: "#00ff00",
    yearStart: 1889,
    yearEnd: 1954,
    photos: [],
    source: "Met Council Data",
  },

  {
    id: 49,
    corridorName: "U of M Transitway",
    routeName: "U of M Transitway",
    terminus: "",
    type: "Streetcar",
    description: "",
    mainColor: "#00ff00",
    yearStart: null,
    yearEnd: 1954,
    photos: [],
    source: "Met Council Data",
    offset: true,
  },

  {
    id: 50,
    corridorName: "Washington Ave N",
    routeName: "Washington Ave N",
    terminus: "",
    type: "Streetcar",
    description: "",
    mainColor: "#00ff00",
    yearStart: 1890,
    yearEnd: 1954,
    photos: [],
    source: "Met Council Data",
  },

  {
    id: 51,
    corridorName: "Western",
    routeName: "Western",
    terminus: "",
    type: "Streetcar",
    description: "",
    mainColor: "#00ff00",
    yearStart: 1891,
    yearEnd: 1954,
    photos: [],
    source: "Met Council Data",
  },

  {
    id: 52,
    corridorName: "Kenwood",
    routeName: "Kenwood",
    terminus: "",
    type: "Streetcar",
    description: "",
    mainColor: "#00ff00",
    yearStart: 1890,
    yearEnd: 1938,
    photos: [],
    source: "Met Council Data",
  },

  {
    id: 53,
    corridorName: "Grand Ave",
    routeName: "Grand Ave dup?",
    terminus: "",
    type: "Streetcar",
    description: "",
    mainColor: "#00ff00",
    yearStart: 1890,
    yearEnd: 1954,
    photos: [],
    source: "Met Council Data",
  },
];
