import { Corridor } from "./types";

export const CORRIDORS: Array<Corridor> = [
  {
    id: 1,
    DATA_CORRIDOR: "25th St E",
    routeName: "25th St E",
    mainCity: "Minneapolis",
    terminus: "",
    DATA_TYPE: "Streetcar",
    description: "",
    mainColor: "#00ff00",
    yearStart: 1890,
    yearEnd: 1954,
    photos: [],
    sources: "Met Council Data",
  },
  {
    id: 2,
    DATA_CORRIDOR: "28th Ave_34th Ave",
    routeName: "28th Ave to 34th Ave",
    mainCity: "Minneapolis",
    terminus: "",
    DATA_TYPE: "Streetcar",
    description: "North Emerson",
    mainColor: "#00ff00",
    yearStart: 1889,
    yearEnd: 1954,
    photos: [],
    sources: "Met Council Data",
  },

  {
    id: 3,
    DATA_CORRIDOR: "2nd St NE",
    routeName: "2nd St NE",
    terminus: "",
    DATA_TYPE: "Streetcar",
    description: "",
    mainColor: "#00ff00",
    yearStart: 1890,
    yearEnd: 1915,
    photos: [],
    sources: "Met Council Data",
    mainCity: "Minneapolis",
  },
  {
    id: 4,
    DATA_CORRIDOR: "4th Ave",
    routeName: "4th Ave",
    terminus: "",
    DATA_TYPE: "Streetcar",
    description: "",
    mainColor: "#00ff00",
    yearStart: null,
    yearEnd: null,
    photos: [],
    sources: "Met Council Data",
    mainCity: "Minneapolis",
  },
  {
    id: 5,
    DATA_CORRIDOR: "6th Ave N",
    routeName: "6th Ave N",
    terminus: "",
    DATA_TYPE: "Streetcar",
    description: "",
    mainColor: "#00ff00",
    yearStart: 1890,
    yearEnd: 1893,
    photos: [],
    sources: "Met Council Data",
    mainCity: "Minneapolis",
  },
  {
    id: 6,
    DATA_CORRIDOR: "Bloomington Ave",
    routeName: "Bloomington Ave",
    terminus: "",
    DATA_TYPE: "Streetcar",
    description: "",
    mainColor: "#00ff00",
    yearStart: 1892,
    yearEnd: 1933,
    photos: [],
    sources: "Met Council Data",
    mainCity: "Minneapolis",
  },

  {
    id: 8,
    DATA_CORRIDOR: "Broadway",
    routeName: "Broadway",
    terminus: "",
    DATA_TYPE: "Streetcar",
    description: "",
    mainColor: "#00ff00",
    yearStart: 1891,
    yearEnd: 1954,
    photos: [],
    sources: "Met Council Data",
    mainCity: "Minneapolis",
  },

  {
    id: 9,
    DATA_CORRIDOR: "Bryant Ave S",
    routeName: "Bryant Ave S",
    terminus: "",
    DATA_TYPE: "Streetcar",
    description: "Terminus at 56th St",
    mainColor: "#00ff00",
    yearStart: 1890,
    yearEnd: 1954,
    photos: [],
    sources: "Met Council Data",
    mainCity: "Minneapolis",
  },

  {
    id: 10,
    DATA_CORRIDOR: "Bryn Maur",
    routeName: "Bryn Mawr",
    terminus: "",
    DATA_TYPE: "Streetcar",
    description: "",
    mainColor: "#00ff00",
    yearStart: 1890,
    yearEnd: 1933,
    photos: [],
    sources: "Met Council Data",
    mainCity: "Minneapolis",
  },

  {
    id: 11,
    DATA_CORRIDOR: "Cable Car",
    routeName: "Cable Car",
    terminus: "",
    DATA_TYPE: "Cable Car",
    description: "",
    mainColor: "#00ff00",
    yearStart: 1886,
    yearEnd: 1891,
    photos: [],
    sources: "Met Council Data",
    mainCity: "Minneapolis",
  },

  {
    id: 12,
    DATA_CORRIDOR: "Cherokee",
    routeName: "Cherokee",
    terminus: "",
    DATA_TYPE: "Streetcar",
    description: "",
    mainColor: "#00ff00",
    yearStart: 1890,
    yearEnd: 1954,
    photos: [],
    sources: "Met Council Data",
    mainCity: "Saint Paul",
  },

  {
    id: 13,
    DATA_CORRIDOR: "Chicago Ave",
    routeName: "Chicago Ave",
    terminus: "",
    DATA_TYPE: "Streetcar",
    description: "",
    mainColor: "#00ff00",
    yearStart: 1890,
    yearEnd: 1954,
    photos: [],
    sources: "Met Council Data",
    mainCity: "Minneapolis",
  },

  {
    id: 14,
    DATA_CORRIDOR: "Columbia Heights",
    routeName: "Columbia Heights",
    terminus: "",
    DATA_TYPE: "Streetcar",
    description: "",
    mainColor: "#00ff00",
    yearStart: 1891,
    yearEnd: 1954,
    photos: [],
    sources: "Met Council Data",
    mainCity: "Minneapolis",
  },

  {
    id: 15,
    DATA_CORRIDOR: "Como_Harriet_Oak_Xer",
    routeName: "Como Harriet Oak",
    terminus: "",
    DATA_TYPE: "Streetcar",
    description: "",
    mainColor: "#00ff00",
    yearStart: 1880,
    yearEnd: 1954,
    photos: [],
    sources: "Met Council Data",
    mainCity: "Minneapolis",
  },

  {
    id: 16,
    DATA_CORRIDOR: "Dale St",
    routeName: "Dale St",
    terminus: "",
    DATA_TYPE: "Streetcar",
    description: "",
    mainColor: "#00ff00",
    yearStart: 1890,
    yearEnd: 1954,
    photos: [],
    sources: "Met Council Data",
    mainCity: "Saint Paul",
  },

  {
    id: 17,
    DATA_CORRIDOR: "Fort Snelling",
    routeName: "Fort Snelling",
    terminus: "",
    DATA_TYPE: "Streetcar",
    description: "",
    mainColor: "#00ff00",
    yearStart: 1890,
    yearEnd: 1954,
    photos: [],
    sources: "Met Council Data",
  },

  {
    id: 18,
    DATA_CORRIDOR: "Franklin",
    routeName: "Franklin",
    terminus: "",
    DATA_TYPE: "Streetcar",
    description: "",
    mainColor: "#00ff00",
    yearStart: 1889,
    yearEnd: 1954,
    photos: [],
    sources: "Met Council Data",
  },

  {
    id: 19,
    DATA_CORRIDOR: "Glenwood Ave",
    routeName: "Glenwood Ave",
    terminus: "",
    DATA_TYPE: "Streetcar",
    description: "",
    mainColor: "#00ff00",
    yearStart: 1891,
    yearEnd: 1954,
    photos: [],
    sources: "Met Council Data",
    mainCity: "Minneapolis",
  },

  {
    id: 20,
    DATA_CORRIDOR: "Grand Ave S",
    routeName: "Grand Ave S",
    terminus: "",
    DATA_TYPE: "Streetcar",
    description: "",
    mainColor: "#00ff00",
    yearStart: 1890,
    yearEnd: 1954,
    photos: [],
    sources: "Met Council Data",
    mainCity: "Minneapolis",
  },

  {
    id: 21,
    DATA_CORRIDOR: "Hamline",
    routeName: "Hamline",
    terminus: "",
    DATA_TYPE: "Streetcar",
    description: "",
    mainColor: "#00ff00",
    yearStart: 1891,
    yearEnd: 1906,
    photos: [],
    sources: "Met Council Data",
  },

  {
    id: 22,
    DATA_CORRIDOR: "Hazel Park",
    routeName: "Hazel Park",
    terminus: "",
    DATA_TYPE: "Streetcar",
    description: "",
    mainColor: "#00ff00",
    yearStart: 1889,
    yearEnd: 1954,
    photos: [],
    sources: "Met Council Data",
  },

  {
    id: 23,
    DATA_CORRIDOR: "Hope",
    routeName: "Hope",
    terminus: "",
    DATA_TYPE: "Streetcar",
    description: "",
    mainColor: "#00ff00",
    yearStart: 1889,
    yearEnd: 1954,
    photos: [],
    sources: "Met Council Data",
  },

  {
    id: 24,
    DATA_CORRIDOR: "Jackson St",
    routeName: "Jackson St",
    terminus: "",
    DATA_TYPE: "Streetcar",
    description: "",
    mainColor: "#00ff00",
    yearStart: 1892,
    yearEnd: 1938,
    photos: [],
    sources: "Met Council Data",
  },

  {
    id: 25,
    DATA_CORRIDOR: "Johnson St NE",
    routeName: "Johnson St NE",
    terminus: "",
    DATA_TYPE: "Streetcar",
    description: "",
    mainColor: "#00ff00",
    yearStart: 1890,
    yearEnd: 1954,
    photos: [],
    sources: "Met Council Data",
    mainCity: "Minneapolis",
  },

  {
    id: 26,
    DATA_CORRIDOR: "Kenwood_StLouisPark",
    routeName: "Kenwood to St. Louis Park",
    terminus: "",
    DATA_TYPE: "Streetcar",
    description: "",
    mainColor: "#00ff00",
    yearStart: 1891,
    yearEnd: 1954,
    photos: [],
    sources: "Met Council Data",
    mainCity: "Minneapolis",
  },

  {
    id: 27,
    DATA_CORRIDOR: "Maria",
    routeName: "Maria",
    terminus: "",
    DATA_TYPE: "Streetcar",
    description: "",
    mainColor: "#00ff00",
    yearStart: 1889,
    yearEnd: 1954,
    photos: [],
    sources: "Met Council Data",
  },

  {
    id: 28,
    DATA_CORRIDOR: "Minnehaha",
    routeName: "Minnehaha",
    terminus: "",
    DATA_TYPE: "Streetcar",
    description: "",
    mainColor: "#00ff00",
    yearStart: 1890,
    yearEnd: 1954,
    photos: [],
    sources: "Met Council Data",
    mainCity: "Minneapolis",
  },

  {
    id: 29,
    DATA_CORRIDOR: "Mississippi St",
    routeName: "Mississippi St",
    terminus: "",
    DATA_TYPE: "Streetcar",
    description: "",
    mainColor: "#00ff00",
    yearStart: 1890,
    yearEnd: 1954,
    photos: [],
    sources: "Met Council Data",
  },

  {
    id: 30,
    DATA_CORRIDOR: "Monroe St NE",
    routeName: "Monroe St NE",
    terminus: "",
    DATA_TYPE: "Streetcar",
    description: "",
    mainColor: "#00ff00",
    yearStart: 1891,
    yearEnd: 1954,
    photos: [],
    sources: "Met Council Data",
    mainCity: "Minneapolis",
  },

  {
    id: 31,
    DATA_CORRIDOR: "Nicollet",
    routeName: "Nicollet",
    terminus: "",
    DATA_TYPE: "Streetcar",
    description: "",
    mainColor: "#00ff00",
    yearStart: 1890,
    yearEnd: 1954,
    photos: [],
    sources: "Met Council Data",
  },

  {
    id: 32,
    DATA_CORRIDOR: "NW Terminal",
    routeName: "NW Terminal",
    terminus: "",
    DATA_TYPE: "Streetcar",
    description: "",
    mainColor: "#00ff00",
    yearStart: 1890,
    yearEnd: 1954,
    photos: [],
    sources: "Met Council Data",
  },

  {
    id: 33,
    DATA_CORRIDOR: "Payne Ave",
    routeName: "Payne Ave",
    terminus: "",
    DATA_TYPE: "Streetcar",
    description: "",
    mainColor: "#00ff00",
    yearStart: 1889,
    yearEnd: 1954,
    photos: [],
    sources: "Met Council Data",
  },

  {
    id: 34,
    DATA_CORRIDOR: "Penn_Fremont",
    routeName: "Penn Fremont",
    terminus: "",
    DATA_TYPE: "Streetcar",
    description: "",
    mainColor: "#00ff00",
    yearStart: 1891,
    yearEnd: 1954,
    photos: [],
    sources: "Met Council Data",
  },

  {
    id: 35,
    DATA_CORRIDOR: "Phalen",
    routeName: "Phalen",
    terminus: "",
    DATA_TYPE: "Streetcar",
    description: "",
    mainColor: "#00ff00",
    yearStart: 1889,
    yearEnd: 1954,
    photos: [],
    sources: "Met Council Data",
  },

  {
    id: 36,
    DATA_CORRIDOR: "Plymouth Ave",
    routeName: "Plymouth Ave",
    terminus: "",
    DATA_TYPE: "Streetcar",
    description: "",
    mainColor: "#00ff00",
    yearStart: 1890,
    yearEnd: 1954,
    photos: [],
    sources: "Met Council Data",
  },

  {
    id: 37,
    DATA_CORRIDOR: "Randolph",
    routeName: "Randolph",
    terminus: "",
    DATA_TYPE: "Streetcar",
    description: "",
    mainColor: "#00ff00",
    yearStart: 1890,
    yearEnd: 1954,
    photos: [],
    sources: "Met Council Data",
  },

  {
    id: 38,
    DATA_CORRIDOR: "Rice St",
    routeName: "Rice St",
    terminus: "",
    DATA_TYPE: "Streetcar",
    description: "",
    mainColor: "#00ff00",
    yearStart: 1891,
    yearEnd: 1954,
    photos: [],
    sources: "Met Council Data",
  },

  {
    id: 39,
    DATA_CORRIDOR: "Robbinsdale",
    routeName: "Robbinsdale",
    terminus: "",
    DATA_TYPE: "Streetcar",
    description: "",
    mainColor: "#00ff00",
    yearStart: 1890,
    yearEnd: 1954,
    photos: [],
    sources: "Met Council Data",
  },

  {
    id: 40,
    DATA_CORRIDOR: "Robert St",
    routeName: "Robert St",
    terminus: "",
    DATA_TYPE: "Streetcar",
    description: "",
    mainColor: "#00ff00",
    yearStart: 1891,
    yearEnd: 1954,
    photos: [],
    sources: "Met Council Data",
  },

  {
    id: 41,
    DATA_CORRIDOR: "Rondo",
    routeName: "Rondo",
    terminus: "",
    DATA_TYPE: "Streetcar",
    description: "",
    mainColor: "#00ff00",
    yearStart: 1891,
    yearEnd: 1954,
    photos: [],
    sources: "Met Council Data",
  },

  {
    id: 42,
    DATA_CORRIDOR: "Saint Clair",
    routeName: "Saint Clair",
    terminus: "",
    DATA_TYPE: "Streetcar",
    description: "",
    mainColor: "#00ff00",
    yearStart: 1890,
    yearEnd: 1954,
    photos: [],
    sources: "Met Council Data",
  },

  {
    id: 43,
    DATA_CORRIDOR: "Selby Lake",
    routeName: "Selby Lake",
    terminus: "",
    DATA_TYPE: "Streetcar",
    description: "",
    mainColor: "#00ff00",
    yearStart: 1888,
    yearEnd: 1954,
    photos: [],
    sources: "Met Council Data",
  },

  {
    id: 44,
    DATA_CORRIDOR: "Snelling Ave",
    routeName: "Snelling Ave",
    terminus: "",
    DATA_TYPE: "Streetcar",
    description: "",
    mainColor: "#00ff00",
    yearStart: 1891,
    yearEnd: 1954,
    photos: [],
    sources: "Met Council Data",
  },

  {
    id: 45,
    DATA_CORRIDOR: "South St Paul",
    routeName: "South St Paul",
    terminus: "",
    DATA_TYPE: "Streetcar",
    description: "",
    mainColor: "#00ff00",
    yearStart: 1891,
    yearEnd: 1954,
    photos: [],
    sources: "Met Council Data",
  },

  {
    id: 46,
    DATA_CORRIDOR: "StPaul_Minneapolis",
    routeName: "StPaul_Minneapolis",
    terminus: "",
    DATA_TYPE: "Streetcar",
    description: "",
    mainColor: "#00ff00",
    yearStart: 1890,
    yearEnd: 1954,
    photos: [],
    sources: "Met Council Data",
  },

  {
    id: 47,
    DATA_CORRIDOR: "Stryker Ave",
    routeName: "Stryker Ave",
    terminus: "",
    DATA_TYPE: "Streetcar",
    description: "",
    mainColor: "#00ff00",
    yearStart: 1890,
    yearEnd: 1954,
    photos: [],
    sources: "Met Council Data",
  },

  {
    id: 48,
    DATA_CORRIDOR: "Stillwater Streetcar",
    routeName: "Stillwater Streetcar",
    terminus: "",
    DATA_TYPE: "Streetcar",
    description: "",
    mainColor: "#00ff00",
    yearStart: 1889,
    yearEnd: 1954,
    photos: [],
    sources: "Met Council Data",
  },

  {
    id: 49,
    DATA_CORRIDOR: "U of M Transitway",
    routeName: "U of M Transitway",
    terminus: "",
    DATA_TYPE: "Streetcar",
    description: "",
    mainColor: "#00ff00",
    yearStart: null,
    yearEnd: 1954,
    photos: [],
    sources: "Met Council Data",
    overlapIndex: 5,
  },

  {
    id: 50,
    DATA_CORRIDOR: "Washington Ave N",
    routeName: "Washington Ave N",
    terminus: "",
    DATA_TYPE: "Streetcar",
    description: "",
    mainColor: "#00ff00",
    yearStart: 1890,
    yearEnd: 1954,
    photos: [],
    sources: "Met Council Data",
  },

  {
    id: 51,
    DATA_CORRIDOR: "Western",
    routeName: "Western",
    terminus: "",
    DATA_TYPE: "Streetcar",
    description: "",
    mainColor: "#00ff00",
    yearStart: 1891,
    yearEnd: 1954,
    photos: [],
    sources: "Met Council Data",
  },

  {
    id: 52,
    DATA_CORRIDOR: "Kenwood",
    routeName: "Kenwood",
    terminus: "",
    DATA_TYPE: "Streetcar",
    description: "",
    mainColor: "#00ff00",
    yearStart: 1890,
    yearEnd: 1938,
    photos: [],
    sources: "Met Council Data",
  },

  {
    id: 53,
    DATA_CORRIDOR: "Grand Ave",
    routeName: "Grand Ave dup?",
    terminus: "",
    DATA_TYPE: "Streetcar",
    description: "",
    mainColor: "#00ff00",
    yearStart: 1890,
    yearEnd: 1954,
    photos: [],
    sources: "Met Council Data",
  },

  {
    id: 54,
    DATA_CORRIDOR: "Anoka",
    DATA_TYPE: "Streetcar",
    yearStart: 1913,
    yearEnd: 1942,
    routeName: "Mpls - Anoka & Cuyuna Range",
    mainCity: "Anoka",
  },

  {
    id: 55,
    DATA_CORRIDOR: "Excelsior",
    routeName: "Excelsior Express Boat",
    terminus: "",
    DATA_TYPE: "Ferry",
    description: "",
    mainColor: "#00ff00",
    yearStart: 1906,
    yearEnd: 1926,
    photos: [],
    sources: "Met Council Data",
    mainCity: "Minnetonka",
  },
  {
    id: 56,
    DATA_CORRIDOR: "Wildhurst",
    routeName: "Wildhurst Express Boat",
    terminus: "",
    DATA_TYPE: "Ferry",
    description: "",
    mainColor: "#00ff00",
    yearStart: 1906,
    yearEnd: 1926,
    photos: [],
    sources: "Met Council Data",
    mainCity: "Minnetonka",
  },
];
