import P_28TH_AVE_STREETCAR from "./28TH_AVE_STREETCAR.json";
import P_2ND_ST_NE_STREETCAR from "./2ND_ST_NE_STREETCAR.json";
import P_34TH_AVE_STREETCAR from "./34TH_AVE_STREETCAR.json";
import P_4TH_AVE_STREETCAR from "./4TH_AVE_STREETCAR.json";
import P_ANOKA_STREETCAR from "./ANOKA_STREETCAR.json";
import P_BLOOMINGTON_STREETCAR from "./BLOOMINGTON_STREETCAR.json";
import P_BRYANT_AVE_STREETCAR from "./BRYANT_AVE_STREETCAR.json";
import P_CHICAGO_AVE_STREETCAR from "./CHICAGO_AVE_STREETCAR.json";
import P_COMO_HARRIET_STREETCAR from "./COMO_HARRIET_STREETCAR.json";
import P_COMO_HOPKINS_STREETCAR from "./COMO_HOPKINS_STREETCAR.json";
import P_COMO_OAK_STREETCAR from "./COMO_OAK_STREETCAR.json";
import P_DAN_PATCH_TRAIN from "./DAN_PATCH_TRAIN.json";
import P_DEEPHAVEN_STREETCAR from "./DEEPHAVEN_STREETCAR.json";
import P_EXCELSIOR_TONKA_BAY_STREETCAR from "./EXCELSIOR_TONKA_BAY_STREETCAR.json";
import P_GLENWOOD_AVE_STREETCAR from "./GLENWOOD_AVE_STREETCAR.json";
import P_MINNEHAHA_STREETCAR from "./MINNEHAHA_STREETCAR.json";
import P_NICOLLET_STREETCAR from "./NICOLLET_STREETCAR.json";
import P_PENN_FREMONT_STREETCAR from "./PENN_FREMONT_STREETCAR.json";

export const PHOTO_JSON: { [key: string]: any } = {
  P_28TH_AVE_STREETCAR,
  P_2ND_ST_NE_STREETCAR,
  P_34TH_AVE_STREETCAR,
  P_4TH_AVE_STREETCAR,
  P_ANOKA_STREETCAR,
  P_BLOOMINGTON_STREETCAR,
  P_BRYANT_AVE_STREETCAR,
  P_CHICAGO_AVE_STREETCAR,
  P_COMO_HARRIET_STREETCAR,
  P_COMO_HOPKINS_STREETCAR,
  P_COMO_OAK_STREETCAR,
  P_DAN_PATCH_TRAIN,
  P_DEEPHAVEN_STREETCAR,
  P_EXCELSIOR_TONKA_BAY_STREETCAR,
  P_GLENWOOD_AVE_STREETCAR,
  P_MINNEHAHA_STREETCAR,
  P_NICOLLET_STREETCAR,
  P_PENN_FREMONT_STREETCAR,
};
