import P_25TH_ST_E_STREETCAR from "./25TH_ST_E_STREETCAR.json";
import P_28TH_AVE_STREETCAR from "./28TH_AVE_STREETCAR.json";
import P_2ND_ST_NE_STREETCAR from "./2ND_ST_NE_STREETCAR.json";
import P_34TH_AVE_STREETCAR from "./34TH_AVE_STREETCAR.json";
import P_4TH_AVE_STREETCAR from "./4TH_AVE_STREETCAR.json";
import P_6TH_AVE_STREETCAR from "./6TH_AVE_STREETCAR.json";
import P_ANOKA_STREETCAR from "./ANOKA_STREETCAR.json";
import P_BLOOMINGTON_STREETCAR from "./BLOOMINGTON_STREETCAR.json";
import P_BROADWAY_AVE_STREETCAR from "./BROADWAY_AVE_STREETCAR.json";
import P_BRYANT_AVE_STREETCAR from "./BRYANT_AVE_STREETCAR.json";
import P_BRYN_MAWR_STREETCAR from "./BRYN_MAWR_STREETCAR.json";
import P_CHICAGO_AVE_STREETCAR from "./CHICAGO_AVE_STREETCAR.json";
import P_COLUMBIA_HEIGHTS_STREETCAR from "./COLUMBIA_HEIGHTS_STREETCAR.json";
import P_COMO_HARRIET_STREETCAR from "./COMO_HARRIET_STREETCAR.json";
import P_COMO_HOPKINS_STREETCAR from "./COMO_HOPKINS_STREETCAR.json";
import P_COMO_OAK_STREETCAR from "./COMO_OAK_STREETCAR.json";
import P_DALE_ST_STREETCAR from "./DALE_ST_STREETCAR.json";
import P_DAN_PATCH_TRAIN from "./DAN_PATCH_TRAIN.json";
import P_DEEPHAVEN_STREETCAR from "./DEEPHAVEN_STREETCAR.json";
import P_EXCELSIOR_FERRY from "./EXCELSIOR_FERRY.json";
import P_EXCELSIOR_TONKA_BAY_STREETCAR from "./EXCELSIOR_TONKA_BAY_STREETCAR.json";
import P_FORT_SNELLING_MPLS_STREETCAR from "./FORT_SNELLING_MPLS_STREETCAR.json";
import P_FORT_SNELLING_STREETCAR from "./FORT_SNELLING_STREETCAR.json";
import P_FRANKLIN_AVE_STREETCAR from "./FRANKLIN_AVE_STREETCAR.json";
import P_GLENWOOD_AVE_STREETCAR from "./GLENWOOD_AVE_STREETCAR.json";
import P_GRAND_AVE_STREETCAR from "./GRAND_AVE_STREETCAR.json";
import P_GRAND_AVE_S_STREETCAR from "./GRAND_AVE_S_STREETCAR.json";
import P_HAMLINE_STREETCAR from "./HAMLINE_STREETCAR.json";
import P_HAZEL_PARK_STREETCAR from "./HAZEL_PARK_STREETCAR.json";
import P_HOPE_STREETCAR from "./HOPE_STREETCAR.json";
import P_JACKSON_ST_STREETCAR from "./JACKSON_ST_STREETCAR.json";
import P_JOHNSON_ST_NE_STREETCAR from "./JOHNSON_ST_NE_STREETCAR.json";
import P_KENWOOD_SLP_STREETCAR from "./KENWOOD_SLP_STREETCAR.json";
import P_KENWOOD_STREETCAR from "./KENWOOD_STREETCAR.json";
import P_MINNEHAHA_STREETCAR from "./MINNEHAHA_STREETCAR.json";
import P_NICOLLET_STREETCAR from "./NICOLLET_STREETCAR.json";
import P_N_SAINT_PAUL_STREETCAR from "./N_SAINT_PAUL_STREETCAR.json";
import P_PAYNE_AVE_STREETCAR from "./PAYNE_AVE_STREETCAR.json";
import P_PENN_FREMONT_STREETCAR from "./PENN_FREMONT_STREETCAR.json";
import P_PLYMOUTH_AVE_STREETCAR from "./PLYMOUTH_AVE_STREETCAR.json";
import P_RANDOLPH_STREETCAR from "./RANDOLPH_STREETCAR.json";
import P_RICE_ST_STREETCAR from "./RICE_ST_STREETCAR.json";
import P_ROBBINSDALE_STREETCAR from "./ROBBINSDALE_STREETCAR.json";
import P_ROBERT_ST_STREETCAR from "./ROBERT_ST_STREETCAR.json";
import P_RONDO_STREETCAR from "./RONDO_STREETCAR.json";
import P_SAINTPAUL_MINNEAPOLIS_STREETCAR from "./SAINTPAUL_MINNEAPOLIS_STREETCAR.json";
import P_SAINT_CLAIR_STREETCAR from "./SAINT_CLAIR_STREETCAR.json";
import P_SELBY_LAKE_STREETCAR from "./SELBY_LAKE_STREETCAR.json";
import P_SNELLING_AVE_STREETCAR from "./SNELLING_AVE_STREETCAR.json";
import P_SOUTH_ST_PAUL_HASTINGS_STREETCAR from "./SOUTH_ST_PAUL_HASTINGS_STREETCAR.json";
import P_STILLWATER_STREETCAR from "./STILLWATER_STREETCAR.json";
import P_U_OF_M_TRANSITWAY_STREETCAR from "./U_OF_M_TRANSITWAY_STREETCAR.json";
import P_WASHINGTON_AVE_STREETCAR from "./WASHINGTON_AVE_STREETCAR.json";
import P_WESTERN_STREETCAR from "./WESTERN_STREETCAR.json";
import P_WHITE_BEAR_LAKE_STREETCAR from "./WHITE_BEAR_LAKE_STREETCAR.json";
import P_WILDHURST_FERRY from "./WILDHURST_FERRY.json";

export const PHOTO_JSON: { [key: string]: any } = {
  P_25TH_ST_E_STREETCAR,
  P_28TH_AVE_STREETCAR,
  P_2ND_ST_NE_STREETCAR,
  P_34TH_AVE_STREETCAR,
  P_4TH_AVE_STREETCAR,
  P_6TH_AVE_STREETCAR,
  P_ANOKA_STREETCAR,
  P_BLOOMINGTON_STREETCAR,
  P_BROADWAY_AVE_STREETCAR,
  P_BRYANT_AVE_STREETCAR,
  P_BRYN_MAWR_STREETCAR,
  P_CHICAGO_AVE_STREETCAR,
  P_COLUMBIA_HEIGHTS_STREETCAR,
  P_COMO_HARRIET_STREETCAR,
  P_COMO_HOPKINS_STREETCAR,
  P_COMO_OAK_STREETCAR,
  P_DALE_ST_STREETCAR,
  P_DAN_PATCH_TRAIN,
  P_DEEPHAVEN_STREETCAR,
  P_EXCELSIOR_FERRY,
  P_EXCELSIOR_TONKA_BAY_STREETCAR,
  P_FORT_SNELLING_MPLS_STREETCAR,
  P_FORT_SNELLING_STREETCAR,
  P_FRANKLIN_AVE_STREETCAR,
  P_GLENWOOD_AVE_STREETCAR,
  P_GRAND_AVE_STREETCAR,
  P_GRAND_AVE_S_STREETCAR,
  P_HAMLINE_STREETCAR,
  P_HAZEL_PARK_STREETCAR,
  P_HOPE_STREETCAR,
  P_JACKSON_ST_STREETCAR,
  P_JOHNSON_ST_NE_STREETCAR,
  P_KENWOOD_SLP_STREETCAR,
  P_KENWOOD_STREETCAR,
  P_MINNEHAHA_STREETCAR,
  P_NICOLLET_STREETCAR,
  P_N_SAINT_PAUL_STREETCAR,
  P_PAYNE_AVE_STREETCAR,
  P_PENN_FREMONT_STREETCAR,
  P_PLYMOUTH_AVE_STREETCAR,
  P_RANDOLPH_STREETCAR,
  P_RICE_ST_STREETCAR,
  P_ROBBINSDALE_STREETCAR,
  P_ROBERT_ST_STREETCAR,
  P_RONDO_STREETCAR,
  P_SAINTPAUL_MINNEAPOLIS_STREETCAR,
  P_SAINT_CLAIR_STREETCAR,
  P_SELBY_LAKE_STREETCAR,
  P_SNELLING_AVE_STREETCAR,
  P_SOUTH_ST_PAUL_HASTINGS_STREETCAR,
  P_STILLWATER_STREETCAR,
  P_U_OF_M_TRANSITWAY_STREETCAR,
  P_WASHINGTON_AVE_STREETCAR,
  P_WESTERN_STREETCAR,
  P_WHITE_BEAR_LAKE_STREETCAR,
  P_WILDHURST_FERRY,
};
